---

- name: Get and install your certificates for {{ web_server }}
  ansible.builtin.shell:
    cmd: >-
      echo 'y' | bash -c
      'certbot --{{ web_server }}
      --noninteractive
      --agree-tos
      --redirect
      --email {{ certbot_email }}
      -d {{ domain_name }}'

- name: Ensure nginx service is restarted
  ansible.builtin.service:
    name: Nginx
    state: restarted
  changed_when: false
  when: web_server == "nginx"

- name: Ensure apache service is restarted
  ansible.builtin.service:
    name: Apache2
    state: restarted
  changed_when: false
  when: web_server == "apache"
